version: 0.2
run-as: yoctouser

env:
  shell: bash
  # HOME is set to /root even when running as a non-root user.
  variables:
    HOME: "/home/yoctouser"

phases:
  pre_build:
    run-as: root
    commands:
      - echo "Pre build started - [$(date '+%F %H:%M:%S')]"
      - mkdir -p /nfs/sstate-cache && chown -R yoctouser /nfs/sstate-cache
      - mkdir -p /nfs/downloads && chown -R yoctouser /nfs/downloads
      - mkdir -p /nfs/build-output && chown -R yoctouser /nfs/build-output
      - chmod -R 755 /nfs/sstate-cache
      - chmod -R 755 /nfs/downloads
      - chmod -R 755 /nfs/build-output
      - |
          if [[ -n "$PURGE_EFS" ]] ; then
            echo "Starting EFS purge."
            rm -rvf /nfs/downloads/*
            rm -rvf /nfs/sstate-cache/*
            rm -rvf /nfs/build-output/*
          fi
      - echo "Pre build completed - [$(date '+%F %H:%M:%S')]"
  build:
    commands:
      - echo "Build started - [$(date '+%F %H:%M:%S')]"
      - if [ -d .git ]; then rm -rf .git; fi
      - git init $CODEBUILD_SRC_DIR && git add --all && git commit -m 'initial'
      - repo init -u https://github.com/nxp-imx/imx-manifest -b imx-linux-mickledore -m imx-6.1.22-2.0.0.xml
      - repo sync -c --no-tags -j$(nproc --all)
      # If you have not accepted NXP's EULA for these layers, the build will
      # prompt you repeatedly until the timeout. This next line is an
      # intentional barrier to stop the build quickly and get your attention.
      # Please review the licensing required, modify this buildspec to accept
      # and remove the next line to proceed.
      - echo "User input is required." && exit 1
      - MACHINE=imx6ullevk DISTRO=fsl-imx-wayland source ./imx-setup-release.sh
      # Update our local conf to check for CVEs
      - echo 'INHERIT += "cve-check"' >> conf/local.conf
      # this will suppress false positive CVEs
      - echo 'include cve-extra-exclusions.inc' >> conf/local.conf
      # build the image
      - bitbake core-image-minimal
      - echo "Build completed - [$(date '+%F %H:%M:%S')]"
  post_build:
    commands:
      - echo "Post build statred - [$(date '+%F %H:%M:%S')]"
      # Prune old files in our EFS Mounts, that are not accessed by this or any build within 30 days
      - find /nfs/sstate-cache -atime +30 -type f -delete
      # only delete empty dirs
      - find /nfs/sstate-cache -atime +30 -type d -empty -delete
      # Prune old files in our EFS Mounts, that are not accessed by this or any build within 30 days
      - find /nfs/downloads -atime +30 -type f -delete
      # only delete empty dirs
      - find /nfs/downloads -atime +30 -type d -empty -delete
      - echo "Post build completed - [$(date '+%F %H:%M:%S')]"

artifacts:
  discard-paths: true
  files:
    # $TMP_DIR is not supported by imx bsp / distro
    - build/tmp/deploy/images/imx93evk/*
    - build/tmp/log/cve/cve-summary*
