version: 0.2
run-as: yoctouser

env:
  shell: bash

phases:
  pre_build:
    run-as: root
    commands:
      - chown -R yoctouser /sstate-cache
      - chown -R yoctouser /downloads
      - chmod 755 /sstate-cache
      - chmod 755 /downloads
  build:
    commands:
      - git clone https://github.com/aws4embeddedlinux/meta-aws-demos -b v0.0.1
      - cd meta-aws-demos
      - git submodule update --init --recursive
      - echo Build started on `date`
      - . ./init-build-env $TMP_DIR
      - BUILD_DEVICE=qemu bitbake core-image-minimal
  post_build:
    commands:
      # Prune old files in our EFS Mounts, that are not accessed by this or any build within 30 days
      - find /sstate-cache -atime +30 -delete
      - find /downloads -atime +30 -delete

artifacts:
  discard-paths: true
  files:
    - $TMP_DIR/tmp/deploy/images/qemux86-64/core-image-minimal-qemux86-64*
