version: 0.2
run-as: yoctouser

env:
  shell: bash
  # HOME is set to /root even when running as a non-root user.
  variables:
    HOME: "/home/yoctouser"

phases:
  pre_build:
    run-as: root
    commands:
      - echo "Pre build started - [$(date '+%F %H:%M:%S')]"
      - mkdir -p /nfs/sstate-cache && chown -R yoctouser /nfs/sstate-cache
      - mkdir -p /nfs/downloads && chown -R yoctouser /nfs/downloads
      - mkdir -p /nfs/build-output && chown -R yoctouser /nfs/build-output
      - chmod -R 755 /nfs/sstate-cache
      - chmod -R 755 /nfs/downloads
      - chmod -R 755 /nfs/build-output
      - |
          if [[ -n "$PURGE_EFS" ]] ; then
            echo "Starting EFS purge."
            rm -rvf /nfs/downloads/*
            rm -rvf /nfs/sstate-cache/*
            rm -rvf /nfs/build-output/*
          fi
      - echo "Pre build completed - [$(date '+%F %H:%M:%S')]"
  build:
    commands:
      - echo "Build started - [$(date '+%F %H:%M:%S')]"
      # BB_ENV_EXTRAWHITE is still used in Dunfell release and was renamed afterwards to BB_ENV_PASSTHROUGH_ADDITIONS
      - export BB_ENV_EXTRAWHITE=$BB_ENV_PASSTHROUGH_ADDITIONS
      - chmod +x ./build.sh
      - ./build.sh h3ulcb
      - echo "Build completed - [$(date '+%F %H:%M:%S')]"
  post_build:
    commands:
      - echo "Post build statred - [$(date '+%F %H:%M:%S')]"
      # Prune old files in our EFS Mounts, that are not accessed by this or any build within 30 days
      - find /nfs/sstate-cache -atime +30 -type f -delete
      # only delete empty dirs
      - find /nfs/sstate-cache -atime +30 -type d -empty -delete
      # Prune old files in our EFS Mounts, that are not accessed by this or any build within 30 days
      - find /nfs/downloads -atime +30 -type f -delete
      # only delete empty dirs
      - find /nfs/downloads -atime +30 -type d -empty -delete
      - echo "Post build completed - [$(date '+%F %H:%M:%S')]"

artifacts:
  discard-paths: true
  files:
    - h3ulcb/build/tmp/deploy/images/h3ulcb/*
