name: shellcheck
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
jobs:
  Run-Pre-Commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install shellcheck
        run: sudo apt-get install shellcheck
      - name: Run shellcheck
        run: shellcheck assets/*.sh
